version: "3.8"

services:
  rkn-checker:
    build:
      context: .
      dockerfile: Dockerfile
    image: rkn-checker:latest
    container_name: rkn-checker
    ports:
      - "9090:9090"  # gRPC endpoint
      - "80:80"      # REST endpoint
    environment:
      - GRPC_PORT=9090
      - REST_PORT=80
      - UPDATE_INTERVAL=48h
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:80/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - rkn-net

networks:
  rkn-net:
    name: rkn-net
    driver: bridge