// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/delivery/grpc/proto/blocking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_Status = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_Status = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_Status = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_Status = 3
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_delivery_grpc_proto_blocking_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_delivery_grpc_proto_blocking_proto_enumTypes[0]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_blocking_proto_rawDescGZIP(), []int{5, 0}
}

type CheckURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckURLRequest) Reset() {
	*x = CheckURLRequest{}
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckURLRequest) ProtoMessage() {}

func (x *CheckURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckURLRequest.ProtoReflect.Descriptor instead.
func (*CheckURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_blocking_proto_rawDescGZIP(), []int{0}
}

func (x *CheckURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CheckURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocked       bool                   `protobuf:"varint,1,opt,name=blocked,proto3" json:"blocked,omitempty"`
	NormalizedUrl string                 `protobuf:"bytes,2,opt,name=normalized_url,json=normalizedUrl,proto3" json:"normalized_url,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Match         string                 `protobuf:"bytes,4,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckURLResponse) Reset() {
	*x = CheckURLResponse{}
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckURLResponse) ProtoMessage() {}

func (x *CheckURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckURLResponse.ProtoReflect.Descriptor instead.
func (*CheckURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_blocking_proto_rawDescGZIP(), []int{1}
}

func (x *CheckURLResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *CheckURLResponse) GetNormalizedUrl() string {
	if x != nil {
		return x.NormalizedUrl
	}
	return ""
}

func (x *CheckURLResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckURLResponse) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_blocking_proto_rawDescGZIP(), []int{2}
}

type GetStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalEntries    int64                  `protobuf:"varint,1,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	DomainEntries   int64                  `protobuf:"varint,2,opt,name=domain_entries,json=domainEntries,proto3" json:"domain_entries,omitempty"`
	WildcardEntries int64                  `protobuf:"varint,3,opt,name=wildcard_entries,json=wildcardEntries,proto3" json:"wildcard_entries,omitempty"`
	IpEntries       int64                  `protobuf:"varint,4,opt,name=ip_entries,json=ipEntries,proto3" json:"ip_entries,omitempty"`
	UrlPatterns     int64                  `protobuf:"varint,5,opt,name=url_patterns,json=urlPatterns,proto3" json:"url_patterns,omitempty"`
	LastUpdate      string                 `protobuf:"bytes,6,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Version         string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_blocking_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatsResponse) GetTotalEntries() int64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *GetStatsResponse) GetDomainEntries() int64 {
	if x != nil {
		return x.DomainEntries
	}
	return 0
}

func (x *GetStatsResponse) GetWildcardEntries() int64 {
	if x != nil {
		return x.WildcardEntries
	}
	return 0
}

func (x *GetStatsResponse) GetIpEntries() int64 {
	if x != nil {
		return x.IpEntries
	}
	return 0
}

func (x *GetStatsResponse) GetUrlPatterns() int64 {
	if x != nil {
		return x.UrlPatterns
	}
	return 0
}

func (x *GetStatsResponse) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *GetStatsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_blocking_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=blocking.v1.HealthCheckResponse_Status" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_blocking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_blocking_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_delivery_grpc_proto_blocking_proto protoreflect.FileDescriptor

const file_internal_delivery_grpc_proto_blocking_proto_rawDesc = "" +
	"\n" +
	"+internal/delivery/grpc/proto/blocking.proto\x12\vblocking.v1\"#\n" +
	"\x0fCheckURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x81\x01\n" +
	"\x10CheckURLResponse\x12\x18\n" +
	"\ablocked\x18\x01 \x01(\bR\ablocked\x12%\n" +
	"\x0enormalized_url\x18\x02 \x01(\tR\rnormalizedUrl\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x14\n" +
	"\x05match\x18\x04 \x01(\tR\x05match\"\x11\n" +
	"\x0fGetStatsRequest\"\x86\x02\n" +
	"\x10GetStatsResponse\x12#\n" +
	"\rtotal_entries\x18\x01 \x01(\x03R\ftotalEntries\x12%\n" +
	"\x0edomain_entries\x18\x02 \x01(\x03R\rdomainEntries\x12)\n" +
	"\x10wildcard_entries\x18\x03 \x01(\x03R\x0fwildcardEntries\x12\x1d\n" +
	"\n" +
	"ip_entries\x18\x04 \x01(\x03R\tipEntries\x12!\n" +
	"\furl_patterns\x18\x05 \x01(\x03R\vurlPatterns\x12\x1f\n" +
	"\vlast_update\x18\x06 \x01(\tR\n" +
	"lastUpdate\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"\x14\n" +
	"\x12HealthCheckRequest\"\xba\x01\n" +
	"\x13HealthCheckResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.blocking.v1.HealthCheckResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032\xf5\x01\n" +
	"\x0fBlockingService\x12G\n" +
	"\bCheckURL\x12\x1c.blocking.v1.CheckURLRequest\x1a\x1d.blocking.v1.CheckURLResponse\x12G\n" +
	"\bGetStats\x12\x1c.blocking.v1.GetStatsRequest\x1a\x1d.blocking.v1.GetStatsResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.blocking.v1.HealthCheckRequest\x1a .blocking.v1.HealthCheckResponseBBZ@github.com/kerim-dauren/rkn-checker/internal/delivery/grpc/protob\x06proto3"

var (
	file_internal_delivery_grpc_proto_blocking_proto_rawDescOnce sync.Once
	file_internal_delivery_grpc_proto_blocking_proto_rawDescData []byte
)

func file_internal_delivery_grpc_proto_blocking_proto_rawDescGZIP() []byte {
	file_internal_delivery_grpc_proto_blocking_proto_rawDescOnce.Do(func() {
		file_internal_delivery_grpc_proto_blocking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_delivery_grpc_proto_blocking_proto_rawDesc), len(file_internal_delivery_grpc_proto_blocking_proto_rawDesc)))
	})
	return file_internal_delivery_grpc_proto_blocking_proto_rawDescData
}

var file_internal_delivery_grpc_proto_blocking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_delivery_grpc_proto_blocking_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_delivery_grpc_proto_blocking_proto_goTypes = []any{
	(HealthCheckResponse_Status)(0), // 0: blocking.v1.HealthCheckResponse.Status
	(*CheckURLRequest)(nil),         // 1: blocking.v1.CheckURLRequest
	(*CheckURLResponse)(nil),        // 2: blocking.v1.CheckURLResponse
	(*GetStatsRequest)(nil),         // 3: blocking.v1.GetStatsRequest
	(*GetStatsResponse)(nil),        // 4: blocking.v1.GetStatsResponse
	(*HealthCheckRequest)(nil),      // 5: blocking.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 6: blocking.v1.HealthCheckResponse
}
var file_internal_delivery_grpc_proto_blocking_proto_depIdxs = []int32{
	0, // 0: blocking.v1.HealthCheckResponse.status:type_name -> blocking.v1.HealthCheckResponse.Status
	1, // 1: blocking.v1.BlockingService.CheckURL:input_type -> blocking.v1.CheckURLRequest
	3, // 2: blocking.v1.BlockingService.GetStats:input_type -> blocking.v1.GetStatsRequest
	5, // 3: blocking.v1.BlockingService.HealthCheck:input_type -> blocking.v1.HealthCheckRequest
	2, // 4: blocking.v1.BlockingService.CheckURL:output_type -> blocking.v1.CheckURLResponse
	4, // 5: blocking.v1.BlockingService.GetStats:output_type -> blocking.v1.GetStatsResponse
	6, // 6: blocking.v1.BlockingService.HealthCheck:output_type -> blocking.v1.HealthCheckResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_delivery_grpc_proto_blocking_proto_init() }
func file_internal_delivery_grpc_proto_blocking_proto_init() {
	if File_internal_delivery_grpc_proto_blocking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_delivery_grpc_proto_blocking_proto_rawDesc), len(file_internal_delivery_grpc_proto_blocking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_delivery_grpc_proto_blocking_proto_goTypes,
		DependencyIndexes: file_internal_delivery_grpc_proto_blocking_proto_depIdxs,
		EnumInfos:         file_internal_delivery_grpc_proto_blocking_proto_enumTypes,
		MessageInfos:      file_internal_delivery_grpc_proto_blocking_proto_msgTypes,
	}.Build()
	File_internal_delivery_grpc_proto_blocking_proto = out.File
	file_internal_delivery_grpc_proto_blocking_proto_goTypes = nil
	file_internal_delivery_grpc_proto_blocking_proto_depIdxs = nil
}
